### PR TITLE
Tell translator that it only accepts English city name for now.

### PR DESCRIPTION
**Pull request by mayukojpn**
I also added what kind of information of city this plugin need.

### CODE REVIEW

**Comment by iandunn** [comment]
The API should accept most endonyms. I've verified that a variety of languages do work, like `አዲስ አበ`, `白浜町宇佐崎南`, `كراچى`, `Москва`, `Hagåtña`, etc.

There is a known bug where some endonyms aren't working, though, for example: `東京`, `كراچى`,
`تهران`, and `Yaoundé`.

I haven't figured out the cause yet, but the goal of the API is to allow users to enter locations in their native language, rather than having to use English.

**Comment by mayukojpn** [comment]
I totally agree with you that we should support more endonyms for feature! I suggested just kind of first aid because first impression should be important and this fix should be take time.

For Japanese locale, I found `京都市` worked, but people should enter `京都` or `京都府` instead. It was only city name I found while I tried more than 30. I don't believe people will enter 2 city names like `白浜町宇佐崎南` it's like `New York NY` 😕

**Comment by iandunn** [comment]
Thanks for the PR! I'm going to spend some time today looking into the endonym bug again.

**Comment by iandunn** [comment]
That bug was pretty tricky, but I think I mostly fixed it in https://meta.trac.wordpress.org/changeset/5277/

@mayukojpn, can you test again and let me know any specific queries that fail?

I don't think there's a good way to make `京都府` work, because MySQL < `5.7.6` isn't smart enough to know where the word boundaries are in ideographic languages. Let me know if you have any ideas, though. We're just using [the Geonames.org database (ZIP)](http://download.geonames.org/export/dump/cities1000.zip).

**Pull request merged**
